language: haskell
before_install:
  - git clone --quiet git://github.com/diagrams/diagrams-core.git diagrams/diagrams-core
  - git clone --quiet git://github.com/diagrams/diagrams-lib.git diagrams/diagrams-lib
  - cd diagrams
  - cabal install monoid-extras/ dual-tree/ diagrams-core/ diagrams-lib/
  - cd ..