language: haskell
before_install:
  - git clone --quiet git://github.com/diagrams/diagrams-core.git diagrams/diagrams-core
  - git clone --quiet git://github.com/diagrams/diagrams-lib.git diagrams/diagrams-lib

install:
  - sudo ghc-pkg --global unregister cgi
  - sudo ghc-pkg --global unregister HTTP
  - sudo ghc-pkg --global unregister network
  - sudo ghc-pkg --global unregister regex-compat
  - sudo ghc-pkg --global unregister regex-posix
  - sudo ghc-pkg --global unregister parsec
  - sudo ghc-pkg --global unregister regex-base
  - sudo ghc-pkg --global unregister fgl
  - sudo ghc-pkg --global unregister MonadCatchIO-mtl
  - sudo ghc-pkg --global unregister mtl
  - sudo ghc-pkg --global unregister transformers
  - cabal install transformers-0.3.0.0 mtl-2.1.1 parsec-3.1.2
  - cd diagrams
  - cabal install diagrams-core/ diagrams-lib/ --constraint='transformers >= 0.3' --constraint='mtl >= 2.1'
  - cd ..
  - cabal install --only-dependencies --enable-tests --constraint='transformers >= 0.3' --constraint='mtl >= 2.1'

notifications:
  irc:
    channels:
      - irc.freenode.org#diagrams
    skip_join: true
    template:
      - "\x0313diagrams-contrib\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
